sudo: required
language: generic

services:
  - docker

  before_install:
  - docker build -t sophieaylin/docker-react -f Dockerfile.dev .

  script:
  -  docker run -e CI=true sophieaylin/docker-react npm run test